/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppLayoutRouteImport } from './routes/app/_layout'
import { Route as AppPostsIndexRouteImport } from './routes/app/posts/index'
import { Route as AppSettingsTwitterRouteImport } from './routes/app/settings/twitter'
import { Route as AppSettingsOrganizationRouteImport } from './routes/app/settings/organization'
import { Route as AppPostsNewRouteImport } from './routes/app/posts/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/app/dashboard',
  path: '/app/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/app/_layout',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPostsIndexRoute = AppPostsIndexRouteImport.update({
  id: '/app/posts/',
  path: '/app/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsTwitterRoute = AppSettingsTwitterRouteImport.update({
  id: '/app/settings/twitter',
  path: '/app/settings/twitter',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsOrganizationRoute = AppSettingsOrganizationRouteImport.update({
  id: '/app/settings/organization',
  path: '/app/settings/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPostsNewRoute = AppPostsNewRouteImport.update({
  id: '/app/posts/new',
  path: '/app/posts/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppLayoutRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/app/posts/new': typeof AppPostsNewRoute
  '/app/settings/organization': typeof AppSettingsOrganizationRoute
  '/app/settings/twitter': typeof AppSettingsTwitterRoute
  '/app/posts/': typeof AppPostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppLayoutRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/app/posts/new': typeof AppPostsNewRoute
  '/app/settings/organization': typeof AppSettingsOrganizationRoute
  '/app/settings/twitter': typeof AppSettingsTwitterRoute
  '/app/posts': typeof AppPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/_layout': typeof AppLayoutRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/login': typeof AuthLoginRoute
  '/app/posts/new': typeof AppPostsNewRoute
  '/app/settings/organization': typeof AppSettingsOrganizationRoute
  '/app/settings/twitter': typeof AppSettingsTwitterRoute
  '/app/posts/': typeof AppPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/dashboard'
    | '/auth/callback'
    | '/auth/login'
    | '/app/posts/new'
    | '/app/settings/organization'
    | '/app/settings/twitter'
    | '/app/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/dashboard'
    | '/auth/callback'
    | '/auth/login'
    | '/app/posts/new'
    | '/app/settings/organization'
    | '/app/settings/twitter'
    | '/app/posts'
  id:
    | '__root__'
    | '/'
    | '/app/_layout'
    | '/app/dashboard'
    | '/auth/callback'
    | '/auth/login'
    | '/app/posts/new'
    | '/app/settings/organization'
    | '/app/settings/twitter'
    | '/app/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLayoutRoute: typeof AppLayoutRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AppPostsNewRoute: typeof AppPostsNewRoute
  AppSettingsOrganizationRoute: typeof AppSettingsOrganizationRoute
  AppSettingsTwitterRoute: typeof AppSettingsTwitterRoute
  AppPostsIndexRoute: typeof AppPostsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/app/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_layout': {
      id: '/app/_layout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/posts/': {
      id: '/app/posts/'
      path: '/app/posts'
      fullPath: '/app/posts/'
      preLoaderRoute: typeof AppPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/twitter': {
      id: '/app/settings/twitter'
      path: '/app/settings/twitter'
      fullPath: '/app/settings/twitter'
      preLoaderRoute: typeof AppSettingsTwitterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/organization': {
      id: '/app/settings/organization'
      path: '/app/settings/organization'
      fullPath: '/app/settings/organization'
      preLoaderRoute: typeof AppSettingsOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/posts/new': {
      id: '/app/posts/new'
      path: '/app/posts/new'
      fullPath: '/app/posts/new'
      preLoaderRoute: typeof AppPostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLayoutRoute: AppLayoutRoute,
  AppDashboardRoute: AppDashboardRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLoginRoute: AuthLoginRoute,
  AppPostsNewRoute: AppPostsNewRoute,
  AppSettingsOrganizationRoute: AppSettingsOrganizationRoute,
  AppSettingsTwitterRoute: AppSettingsTwitterRoute,
  AppPostsIndexRoute: AppPostsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
